language: ruby
rvm:
  - 2.3.0

node_js:
  - 4.2.6

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
